 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
       - store_artifacts:
          path: C:\projects\minesweepersolver\src\MinesweeperSolver\bin\Debug\
